/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PfxButton {
        "buttontype": 'primary' | 'callToAction' | 'outline' | 'text';
    }
}
declare global {
    interface HTMLPfxButtonElement extends Components.PfxButton, HTMLStencilElement {
    }
    var HTMLPfxButtonElement: {
        prototype: HTMLPfxButtonElement;
        new (): HTMLPfxButtonElement;
    };
    interface HTMLElementTagNameMap {
        "pfx-button": HTMLPfxButtonElement;
    }
}
declare namespace LocalJSX {
    interface PfxButton {
        "buttontype"?: 'primary' | 'callToAction' | 'outline' | 'text';
    }
    interface IntrinsicElements {
        "pfx-button": PfxButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pfx-button": LocalJSX.PfxButton & JSXBase.HTMLAttributes<HTMLPfxButtonElement>;
        }
    }
}
